### ISSUE TITLE
current implementation only accepts 3 digit logger IDs

### ISSUE THREAD

**Issue by mreinart** [Turbo87/igc-filename-parser#68]
6 digits should be allowed - see igc_fr_specification_2022_with_al7_2022-1-31.pdf
  - A2.5.1 Long file name style
  - example: 2021-05-15-MMM-XXXXXX-01.IGC
      - MMM = manufacturer's three-letter IGC identifier
      - XXXXXX = unique FR Serial ID (S/ID); 6 alphanumeric characters - 6 digits for the logger id
  - Note: The XXXXXX field has 6-characters, with hyphens at the start and end, with leading zeros if necessary to make up the 6 characters. It can also be used by a manufacturer to differentiate between different FR types, such as using the first characters to indicate each FR type. 
      - Stodeus UltraBip example: 2022-12-16-XSD-UB2F17-02.igc

**Comment by Turbo87** [comment]
interesting... https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf states:

> XXXX = unique FR Serial ID (S/ID); 3 or more alphanumeric characters (see the note below)
>
> Note: The XXXX field is not limited in the number of characters but by the hyphens at the start and end of the field. This
can be used by a manufacturer to differentiate between different FR types, such as by having a different first Serial
ID/letter for each FR type. 

I love how the IGC is making breaking changes like that without existing devices being able to comply with it... 🙄 

but yes, it should probably support more than three characters 😅

**Comment by mreinart** [comment]
see pull request #69

**Comment by mreinart** [comment]
> I love how the IGC is making breaking changes like that without existing devices being able to comply with it... 🙄

agree :-)
